src/SharifJobPortal/urls.py
from django.conf.urls 	import patterns, include, url
from django.contrib 	import admin
from django.conf        import settings
from SharifJobPortal.views import index, home
from utils.views        import zedit_preview
from ui_test.views 		import show_template
from accounts.views     import *
from jobs.views         import *
import userpanel_urls

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('')

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))


urlpatterns += patterns('',
    url(r'^$', index),
    url(r'^home/$', home),
    url(r'^zedit/preview/$', zedit_preview),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^userpanel/',  include(userpanel_urls)),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^search/', include('search.urls')),
    url(r'^jobs/', include('jobs.urls')),
    
    url(r'^employer/(?P<username>\w+)/', profile_employer),
    url(r'^user/(?P<username>\w+)/', profile_jobseeker),
    
    url(r'^comments/employer/(?P<employer_id>\d+)/', profile_employer_comments),
    url(r'^rate/employer/(?P<employer_id>\d+)/', profile_employer_rate),
    url(r'^comments/job/(?P<job_id>\d+)/', job_comment),
    url(r'^rate/job/(?P<job_id>\d+)/', job_rate),


    url(r'^cv/(?P<jobseeker_id>\d+)/', profile_jobseeker_getcv),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	# url(r'^ajax/(?P<template>(\w|[/])+)/$', show_template),
	# url(r'^(?P<template>\w+)/$', show_template),
)

src/jobs/urls.py
from django.conf.urls 	import patterns, url
from jobs.views 		import *

urlpatterns = patterns('',
    url(r'apply/(?P<jobid>\d+)$', applyJob),
    url(r'^refuse/(?P<jobid>\d+)$', refuseJob),
    url(r'^delete/(?P<jobid>\d+)$', deleteJob),
    url(r'^edit/(?P<jobid>\d+)/$', editJob),
    url(r'^new/$', newJob),
    url(r'^offers/accept/(?P<offerid>\d+)$', acceptOffer),
    url(r'^offers/reject/(?P<offerid>\d+)$', rejectOffer),
    url(r'^opportunity/zedit/(?P<opportunity_id>\d+)/$', job_opportunity_pages),
    url(r'^opportunity/skills/(?P<opportunity_id>\d+)/$', job_opportunity_skills),
    url(r'^(?P<jobid>\d+)/$', jobPage),
)

src/account/models.py
from django.db import models


# Create your models here.

class User(models.User):

    address = models.CharField(max_length=300)
    postalCode = models.CharField(max_length=15)
    phoneNumber = models.CharField(max_length=15)
    image = models.URLField()
    city = models.CharField(max_length=20)
    personalPage = models.ForeignKey(PersonalPage , unique=True)




class Employer(models.Model):
    companyName = models.CharField(max_length=30)
    PUBLIC = 0
    PRIVATE = 1
    SEMI_PRIVATE = 2

    COMPANY_TYPE_CHOICES = (
        (PUBLIC , 'دولتی') ,
        (PRIVATE , 'خصوصی'),
        (SEMI_PRIVATE , 'نیمه خصوصی'),
    )
    companyType = models.PositiveSmallIntegerField( choices=COMPANY_TYPE_CHOICES , default=PUBLIC)
    registrationNumber = models.CharField(max_length=20)
    contactEmail = models.EmailField()
    webSite = models.URLField()
    establishDate = models.DateField()
    user = models.ForeignKey(User , unique=True)


class JobSeeker(models.Model):
    birthDate = models.DateField()

    MALE = 0
    FEMALE = 1
    SEX_CHOICES = (
        (MALE , 'مرد'),
        (FEMALE , 'زن'),
    )
    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES , default=FEMALE)

    PART_TIME = 0
    FULL_TIME = 1
    UNEMPLOYED = 2
    JOB_STATUS_CHOICES = (
        (PART_TIME , 'پاره وقت'),
        (FULL_TIME , 'تمام وقت'),
        (UNEMPLOYED , 'بیکار'),
    )
    job_status = models.PositiveSmallIntegerField(choices=JOB_STATUS_CHOICES , default=UNEMPLOYED)

    cv = models.URLField()
    user = models.ForeignKey(User , unique=True)


class PersonalPage(models.Model):
    aboutMe = models.TextField(max_length=3000)
    background = models.TextField(max_length=3000)
    projects = models.TextField(max_length=3000)


class Record(models.Model):
    user = models.ForeignKey(User)
    startDate = models.DateField()
    endDate = models.DateField()
    position = models.CharField(max_length=20)
    companyName = models.CharField(max_length=30)

src/jobs/models.py
#coding=utf-8
from django.db                  import models
from django.utils.safestring    import mark_safe
from accounts.models            import Employer, JobSeeker
import social_network.models

class JobOpportunity(models.Model):
    user = models.ForeignKey(Employer)
    name = models.CharField(max_length=50)

    MALE = 0
    FEMALE = 1
    BOTH = 2

    SEX_CHOICES = (
        (MALE, 'مرد'),
        (FEMALE, 'زن'),
        (BOTH, 'مرد-زن'),
    )

    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES , default=BOTH)
    baseSalary = models.IntegerField()
    number = models.IntegerField()
    expireDate = models.DateField()


    def _get_rate(self):
        ratings = social_network.models.RateForOpportunity.objects.all().filter(opportunity__id = self.id)
        frate = 0.0
        for r in ratings:
            frate += r.rate
        if len(ratings) == 0 or frate == 0.0:
            frate = 0
        else:
            frate /= len(ratings)
        return int(round(frate))
    rate = property(_get_rate)

    def __unicode__(self):
        # return mark_safe('<a href="/jobs/' + str(self.id) + '/">' + self.name + '</a>')
        return self.name

class JobOpportunityPage(models.Model):
    opportunity = models.ForeignKey(JobOpportunity, related_name='pages')
    title   = models.CharField(max_length = 100)
    content = models.TextField(null=True, blank=True)
    
class Skill(models.Model):
    name = models.CharField(max_length=50, unique=True)
    user = models.ManyToManyField(JobSeeker, related_name = 'skills', blank = True, null = True)
    opportunity = models.ManyToManyField(JobOpportunity, related_name = 'opSkills', blank = True, null = True)
    class Meta:
        verbose_name = 'مهارت'
        verbose_name_plural = 'مهارت ها'

    def __unicode__(self):
        return self.name



class JobOffer(models.Model):
    jobSeeker = models.ForeignKey(JobSeeker)
    jobOpportunity = models.ForeignKey(JobOpportunity, related_name='offers')
    offerDate = models.DateField()

    ACCEPTED = 0
    REJECTED = 1
    PENDING = 2
    STATE_CHOICES = (
        (ACCEPTED , 'قبول شده'),
        (REJECTED ,'رد شده'),
        (PENDING ,'معلق'),
    )
    state = models.PositiveSmallIntegerField(choices=STATE_CHOICES , default=PENDING)

    JOBSEEKER_TO_EMPLOYER = 0
    EMPLOYER_TO_JOBSEEKER = 1
    MODE_CHOICES = (
        (JOBSEEKER_TO_EMPLOYER ,'کارجو به کارفرما'),
        (EMPLOYER_TO_JOBSEEKER ,'کارفرما به کارجو'),
    )
    mode = models.PositiveSmallIntegerField(choices=MODE_CHOICES , default=JOBSEEKER_TO_EMPLOYER)
    date = models.DateField(auto_now_add=True)

src/jobs/forms.py
from django import forms
from jobs.models import JobOpportunity

class JobForm(forms.ModelForm):
    class Meta:
        model = JobOpportunity
        fields = ['name', 'sex', 'baseSalary', 'number', 'expireDate']

src/jobs/views.py
#coding=utf-8

from datetime                       import datetime
from django.core.serializers        import json
from django.http.response           import HttpResponse
from django.views.decorators.csrf   import csrf_exempt
from django.core.paginator          import Paginator
from django.core.exceptions         import PermissionDenied

from accounts.decorators            import *
from accounts.views                 import userpanel_jobs
from jobs.forms                     import JobForm
from jobs.models                    import *
from social_network.models          import *
from social_network.functions       import *
from utils.functions                import json_response, template

@jobseeker_required
def applyJob(request, jobid):
    print 'hey'
    print jobid
    job = JobOpportunity.objects.get(id = jobid)
    user = request.userprofile
    response = {}
    if not JobOffer.objects.filter(jobSeeker = user, jobOpportunity = job).exists():
        JobOffer.objects.create(jobSeeker = user, jobOpportunity = job, offerDate = datetime.now())
        response['done'] = True
    else:
        response['done'] = False
    return json_response(response)

@jobseeker_required
def refuseJob(request, jobid):
    job = JobOpportunity.objects.get(id = jobid)
    user = request.userprofile
    response = {}
    if JobOffer.objects.filter(jobSeeker = user, jobOpportunity = job).exists():
        JobOffer.objects.filter(jobSeeker = user, jobOpportunity = job).delete()
        response['done'] = True
    else:
        response['done'] = False
    return json_response(response)

@employer_required
def acceptOffer(request, offerid):
    offer = JobOffer.objects.get(id = offerid)
    offer.state = 0
    offer.offerDate = datetime.now()
    offer.save()
    Event_JobOffer.create(initial_user=offer.jobSeeker, jobOffer=offer)
    return json_response({})

@employer_required
def rejectOffer(request, offerid):
    offer = JobOffer.objects.get(id = offerid)
    offer.state = 1
    offer.save()
    return json_response({})

@employer_required
def deleteJob(request, jobid):
    JobOpportunity.objects.get(id = jobid).delete()
    return json_response({})

@employer_required
def editJob(request, jobid):
    job = JobOpportunity.objects.get(id = jobid)
    show_extra = False
    if request.method == "POST":
        form = JobForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            show_extra = True
            return userpanel_jobs(request)
    else:
        show_extra = True
        form = JobForm(instance = job)
    return template(request, 'userpanel/employer/editJob.html', {'form' : form, 'show_extra': show_extra})

@employer_required
def newJob(request):
    show_extra = False
    if request.method == "POST":
        form = JobForm(request.POST)
        if form.is_valid():
            job = form.save(False)
            job.user = request.userprofile
            job.save()
            show_extra = True
            return template(request, 'userpanel/employer/editJob.html', {'form' : form, 'show_extra': True, 'scroll_to_extra': True})
    else:
        form = JobForm()
    return template(request, 'userpanel/employer/editJob.html', {'form' : form, 'show_extra':show_extra})

def jobPage(request, jobid):
    job = JobOpportunity.objects.get(id = jobid)
    skills = map(lambda x: x.name, job.opSkills.all())
    pages = list(job.pages.all())
    return template(request, 'jobs/jobsPage.html', {'job' : job, 'skills':skills, 'pages':pages})


@csrf_exempt
def job_opportunity_pages(request, opportunity_id):
    action = request.POST.get('action', '')
    try:
        opportunity = JobOpportunity.objects.get(pk = opportunity_id)
        if action == 'save':
            page_id = request.POST['page_id']
            content = request.POST['content']
            page = JobOpportunityPage.objects.get(pk = page_id)
            # if page.opportunity.id != opportunity_id:
            #     raise PermissionDenied
            page.content = content
            page.save()
            return json_response({'result': 'success'})

        elif action == 'remove':
            page_id = request.POST['page_id']
            page = JobOpportunityPage.objects.get(pk = page_id)
            if page.opportunity.id != opportunity_id:
                raise PermissionDenied
            page.delete()
            return json_response({'result': 'success'})

        elif action == 'add':
            title = request.POST['title']
            page = JobOpportunityPage.objects.create(opportunity=opportunity, title=title)
            page = {'page_id': page.id, 'title':page.title, 'content': page.content}
            return json_response({'result': 'success', 'page': page})

        elif action == 'list':
            pages = JobOpportunityPage.objects.filter(opportunity=opportunity)
            pages = map(lambda x: {'page_id': x.id, 'title':x.title, 'content': x.content}, pages)
            return json_response({'result': 'success', 'pages': pages})

    except Exception as e:
        raise e
        return json_response({'result': 'fail'})

@csrf_exempt
def job_opportunity_skills(request, opportunity_id):
    if request.method == 'POST':
        action = request.POST.get('action')
        try:
            opportunity = JobOpportunity.objects.get(pk = opportunity_id)
        except:
            return json_response({'result': 'fail', 'error': 'job opportunity not found'})

        if action == 'list possible':
            query = request.POST.get('query', '')
            if query == '':
                skills = Skill.objects.all()
            else:
                skills = Skill.objects.filter(name__contains = query)

            skills = map(lambda x: x.name, skills)
            return json_response({'result': 'success', 'skills': skills})

        elif action == 'list current':
            query = request.POST.get('query', '')
            if query == '':
                skills = opportunity.opSkills.all() 
            else:
                skills = opportunity.opSkills.filter(name__contains = query)
            skills = map(lambda x: x.name, skills)
            return json_response({'result': 'success', 'skills': skills})

        elif action == 'add current':
            skill = request.POST.get('skill', '')
            try:
                opportunity.opSkills.get(name=skill)
            except:
                skill = Skill.objects.get_or_create(name=skill)[0]
                opportunity.opSkills.add(skill)

            skills = opportunity.opSkills.all()
            skills = map(lambda x: x.name, skills)
            return json_response({'result': 'success', 'skills': skills})

        elif action == 'remove current':
            skill = request.POST.get('skill', '')
            try:
                skill = Skill.objects.get(name=skill)
                opportunity.opSkills.remove(skill)
            except:
                pass

            skills = opportunity.opSkills.all()
            skills = map(lambda x: x.name, skills)
            return json_response({'result': 'success', 'skills': skills})
    else:
        return json_response({'result': 'fail', 'error': 'get not supported'})

def comment_to_dict(comment):
    data =  {
        'author': comment.user.full_name,
        'author_url': comment.user.profilePage,
        'date': 'همین الان',
        'content': comment.body
    }

    if comment.user.image:
        data['image'] =  comment.user.image.url
    else:
        data['image'] =  '/static/images/profilepic.png'

    return data

@csrf_exempt
def job_comment(request, job_id):
    try:
        job = JobOpportunity.objects.get(pk = job_id)
    except:
        return json_response({'result':'fail', 'error':'job not found'})

    def list_comments(page, page_size):
        comments = CommentOnOpportunity.objects.filter(opportunity = job).order_by('-time')
        p = Paginator(comments, page_size)
        if page > p.num_pages:
            page = p.num_pages
        if page < 0:
            page = 0
        comments = map(comment_to_dict, p.page(page).object_list)
        return json_response({'result': 'success', 'page':page, 'pageCount':p.num_pages , 'comments': comments})

    if request.method == 'POST':
        action = request.POST['action']
        if action == 'list':
            page_size = request.POST.get('page_size', 4)
            page      = int(request.POST.get('page', 1))
            return list_comments(page, page_size)

        elif action == 'add':
            page_size = request.POST.get('page_size', 4)
            body = request.POST['comment']
            comment  = CommentOnOpportunity.objects.create(opportunity = job, user = request.userprofile, body = body)
            if request.userprofile.is_jobseeker():
                Event_CommentOnOpportunity.objects.create(comment=comment, initial_user=request.userprofile)

            return list_comments(1, page_size)
    else:
        return json_response({'result': 'fail', 'error': 'get not supported'})

@csrf_exempt
def job_rate(request, job_id):
    if request.method == 'POST':
        try:
            job = JobOpportunity.objects.get(pk = job_id)
        except:
            return json_response({'result': 'fail', 'error': 'job does not exist'})

        if request.has_profile and request.userprofile.is_jobseeker():
            try:
                rate = int(request.POST['rate'])
            except:
                return json_response({'result': 'fail', 'error': 'no rate given'})

            rate_opportunity(request.userprofile, job, rate)
            return json_response({'result': 'success'})
    else:
        return json_response({'result': 'fail', 'error': 'get not supported'})

templates/userpanel/jobseeker/changejobseekerinfo.html
{% extends 'userpanel/userpanel.html' %}
{% load filters %}
{% load staticfiles %}

{% block content-title %}
تغییر مشخصات
{% endblock %}

{% block content %}
<div id="jobseekerinfoform" class="infoform">
    {% if state == 'success' %}
        <div class="change success">
            تغییرات با موفقیت ثبت شد
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <h3 class="formheader">مشخصات کاربری</h3>
        <div id="userinfoform" class="ui small form userinfo formpart">
                {% csrf_token %}
                <div class="two fields">
                    {{userform.first_name|semfield}}
                    {{userform.last_name|semfield}}
                </div>
                <div class="two fields">
                    {{userform.email|addclass:'ltr'|semfield}}
                    {{userform.phoneNumber|semfield}}
                </div>
                <div class="two fields">
                    {{userform.address|semfield}}
                    {{userform.postalCode|semfield}}
                </div>
                <div class="two fields">
                    {{userform.city|addclass:"chosen-select"|semfield}}
                    <div class="small field">
                        <label for="id_image">عکس</label>
                        {% if user.userprofile.image %}
                            <div class="image clear">
                                <input id="image-clear_id" name="image-clear" type='checkbox'>
                                <label for="image-clear_id">پاک کردن</label>
                            </div>
                        {% endif %}
                        <input type="file" id="id_image" name="image">
                        {% if user.userprofile.image %}
                            <img class="profilepic" src="/media/{{user.userprofile.image}}">
                        {% else %}
                            <img class="profilepic" src="/static/images/profilepic.png">
                        {% endif %}
                    </div>  
                </div>  
        </div>

        <h3>مشخصات کاری</h3>
        <div class="ui basic small form segment formpart workinfo">
            <div class="two fields">
                {{jobsform.job_status|addclass:"chosen-select"|semfield}}
                <div class="cv field">
                    <label for="id_cv">کارنامک کاری</label>
                    {% if jobsform.cv.value %}
                    <div class="current cv">
                        در حال حاضر:
                        <a href="/media/{{jobsform.cv.value}}">{{jobsform.cv.value}}</a>
                        <div class="remove">
                            <input id="cv-clear_id" name="cv-clear" type='checkbox'>
                            <label for="cv-clear_id">پاک کردن</label>
                        </div>
                    </div>
                    تغییر
                    {% endif %}
                    <input type="file" id="id_cv" name="cv">
                </div>
            </div>
            <button class="ui small blue submit button" type="submit">ثبت</button>
        </div>
    </form>

    <h3>مهارت‌ها</h3>
    <div class="ui basic segment formpart skills">
        <div class="skill chooser">                 
        </div>
    </div>

    <h3>حریم شخصی</h3>
    <div class="ui segment formpart privacy">
        {% for i in '11' %}
            <div class="privacy part">
                <div class="{% cycle 'profile' 'resume' %} privacy">
                    <h4>{% cycle 'امکان دیدن صفحه شخصی' 'امکان دریافت کارنامک کاری'%}</h4>
                    <div class="ui checkbox public access">
                      <input type="checkbox" name="public">
                      <label>دسترسی عمومی</label>
                    </div>
                    {% for j in '11' %}
                        <div class="ui selection dropdown {% cycle 'jobseeker' 'employer' %} privacy">
                          <input type="hidden" name="privacyfield">
                          <div class="text"></div>
                          <i class="dropdown icon"></i>
                          <div class="menu">
                            <div class="item" data-value="0">{% cycle 'هیچ کارجویی' 'هیچ کارفرمایی' %}</div>
                            <div class="item" data-value="1">{% cycle 'کارجویان دوست' 'کارفرمایانی که درخواست استخدام داده‌اید'%}</div>
                            <div class="item" data-value="2">{% cycle 'همه‌ی کارجویان' 'همه کارفرمایان'%}</div>
                          </div>
                        </div>
                        
                    {% endfor %}
                </div>
            </div>    
        {% endfor %}
    </div>

    <h3>صفحه‌های شخصی</h3>
    <div class="ui basic segment formpart imageupload">
        <div class="zedit container">
        </div>
    </div>  
</div>
{% endblock %}

{% block style %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'markitup/skins/simple/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'markitup/sets/markdown/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/zedit.css' %}">
    <style type="text/css">
        .formpart.workinfo{
            margin-right: 30px;
        }
        .formpart.workinfo .cv.field .current.cv{
            margin-top: 20px;
            margin-bottom: 20px;
        }
        .formpart.workinfo .cv.field .current.cv a{
            margin-right: 10px;
        }
        .formpart.workinfo .cv.field .current.cv .remove{
            margin-top: 10px;
        }

        .formpart.privacy {
            padding-bottom: 40px;
            padding-right: 70px;
        }
        .formpart.privacy .privacy.part:first-child{
            margin-bottom: 30px;
        }
        .formpart.privacy .privacy .jobseeker.privacy {
            margin-right: 190px;
        }
        .formpart.privacy .privacy .employer.privacy {
            margin-right: 20px;
        }

        .formpart.privacy .privacy .public.access {
            margin-right: 190px;
            margin-bottom: 20px;
            display: block;
        }

        .formpart.privacy .privacy .dropdown .menu .item{
            z-index: 4000;
        }
    </style>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/rslides.js' %}"></script>
    <script type="text/javascript" src="{% static 'markitup/jquery.markitup.js' %}"></script>
    <script type="text/javascript" src="{% static 'markitup/sets/markdown/set.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/zedit.js' %}"></script>
    <script type="text/javascript">
        $(function(){

            function changeFocus(){
                var active = this;
                $('.formpart').each(function(index){
                    if(this == active){
                        $(this).fadeTo(300, 1.0);
                    }else{
                        $(this).fadeTo(300, 0.5);
                    }
                })

            }
            $('.formpart').hover(changeFocus);

            $('.zedit.container').zedit({
                url: '/userpanel/companyinfo/zedit/',
                showAddForm: true
            });

            $('.skill.chooser').skills({
                url: '/userpanel/info/skills/'
            });

            function setAccessElements(_){
                if(_.access_profile_public){
                    $('.formpart.privacy .profile.privacy .public.checkbox').checkbox('enable');
                    $('.formpart.privacy .profile.privacy .selection.dropdown').hide();
                }else{
                    $('.formpart.privacy .profile.privacy .public.checkbox').checkbox('disable');
                    $('.formpart.privacy .profile.privacy .selection.dropdown').show();
                }
                if(_.access_cv_public){
                    $('.formpart.privacy .resume.privacy .public.checkbox').checkbox('enable');
                    $('.formpart.privacy .resume.privacy .selection.dropdown').hide();
                }else{
                    $('.formpart.privacy .resume.privacy .public.checkbox').checkbox('disable');
                    $('.formpart.privacy .resume.privacy .selection.dropdown').show();
                }
                $('.formpart.privacy .profile.privacy .jobseeker.dropdown')
                    .dropdown('set selected', _.access_profile_jobseeker)
                    .dropdown('set value', _.access_profile_jobseeker);
                $('.formpart.privacy .profile.privacy .employer.dropdown')
                    .dropdown('set selected', _.access_profile_employer)
                    .dropdown('set value', _.access_profile_employer);
                $('.formpart.privacy .resume.privacy .jobseeker.dropdown')
                    .dropdown('set selected', _.access_cv_jobseeker)
                    .dropdown('set value', _.access_cv_jobseeker);
                $('.formpart.privacy .resume.privacy .employer.dropdown')
                    .dropdown('set selected', _.access_cv_employer)
                    .dropdown('set value', _.access_cv_employer);
            }

            function sendAccessData(){
                var accessData = {
                    access_profile_public: $('.formpart.privacy .profile.privacy .public.checkbox input')[0].checked,
                    access_profile_jobseeker: $('.formpart.privacy .profile.privacy .jobseeker.dropdown').dropdown('get value'),
                    access_profile_employer: $('.formpart.privacy .profile.privacy .employer.dropdown').dropdown('get value'),
                    access_cv_public: $('.formpart.privacy .resume.privacy .public.checkbox input')[0].checked,
                    access_cv_jobseeker: $('.formpart.privacy .resume.privacy .jobseeker.dropdown').dropdown('get value'),
                    access_cv_employer: $('.formpart.privacy .resume.privacy .employer.dropdown').dropdown('get value')
                };
                $.ajax({
                    url: '/userpanel/info/privacy/',
                    type: 'post',
                    data: accessData,
                    dataType: 'json',
                    success:function(data){
                        if(data.result == 'success'){
                            setAccessElements(data.permissions);
                        }else{
                            console.log(data);
                        }
                    }
                });
            }

            access = {
                access_profile_public:      {{user.userprofile.access_profile_public|jsbool}},
                access_profile_jobseeker:   {{user.userprofile.access_profile_jobseeker}},
                access_profile_employer:    {{user.userprofile.access_profile_employer}},
                access_cv_public:           {{user.userprofile.access_cv_public|jsbool}},
                access_cv_jobseeker:        {{user.userprofile.access_cv_jobseeker}},
                access_cv_employer:         {{user.userprofile.access_cv_employer}}
            }
            setAccessElements(access);


            $('.formpart.privacy .dropdown.selection').dropdown('setting', 'onChange', sendAccessData);
            $('.formpart.privacy .privacy .public.checkbox').click(sendAccessData);

            $(".chosen-select").chosen({
                disable_search_threshold: 10,
                width: '60%'
            });
        })
    </script>
{% endblock %}