src/SharifJobPortal/urls.py
from django.conf.urls 	import patterns, include, url
from django.contrib 	import admin
from django.conf        import settings
from SharifJobPortal.views import index, home
from utils.views        import zedit_preview
from ui_test.views 		import show_template
from accounts.views     import *
from jobs.views         import *
import userpanel_urls

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('')

if settings.DEBUG:
    urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}))


urlpatterns += patterns('',
    url(r'^$', index),
    url(r'^home/$', home),
    url(r'^zedit/preview/$', zedit_preview),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^userpanel/',  include(userpanel_urls)),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^search/', include('search.urls')),
    url(r'^jobs/', include('jobs.urls')),
    
    url(r'^employer/(?P<username>\w+)/', profile_employer),
    url(r'^user/(?P<username>\w+)/', profile_jobseeker),
    
    url(r'^comments/employer/(?P<employer_id>\d+)/', profile_employer_comments),
    url(r'^rate/employer/(?P<employer_id>\d+)/', profile_employer_rate),
    url(r'^comments/job/(?P<job_id>\d+)/', job_comment),
    url(r'^rate/job/(?P<job_id>\d+)/', job_rate),


    url(r'^cv/(?P<jobseeker_id>\d+)/', profile_jobseeker_getcv),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	# url(r'^ajax/(?P<template>(\w|[/])+)/$', show_template),
	# url(r'^(?P<template>\w+)/$', show_template),
)

src/jobs/urls.py
from django.conf.urls 	import patterns, url
from jobs.views 		import *

urlpatterns = patterns('',
    url(r'apply/(?P<jobid>\d+)$', applyJob),
    url(r'^refuse/(?P<jobid>\d+)$', refuseJob),
    url(r'^delete/(?P<jobid>\d+)$', deleteJob),
    url(r'^edit/(?P<jobid>\d+)/$', editJob),
    url(r'^new/$', newJob),
    url(r'^offers/accept/(?P<offerid>\d+)$', acceptOffer),
    url(r'^offers/reject/(?P<offerid>\d+)$', rejectOffer),
    url(r'^opportunity/zedit/(?P<opportunity_id>\d+)/$', job_opportunity_pages),
    url(r'^opportunity/skills/(?P<opportunity_id>\d+)/$', job_opportunity_skills),
    url(r'^(?P<jobid>\d+)/$', jobPage),
)

src/search/urls.py
from django.conf.urls import patterns, url
from views import opSearch, userSearch, skillSearch, updateRate

urlpatterns = patterns('',
	url(r'^$', opSearch),
	url(r'^op$', opSearch),
    url(r'^user$', userSearch),
    url(r'^skill/$', skillSearch),
    url(r'^rate/$', updateRate),
)

src/account/models.py
from django.db import models


# Create your models here.

class User(models.User):

    address = models.CharField(max_length=300)
    postalCode = models.CharField(max_length=15)
    phoneNumber = models.CharField(max_length=15)
    image = models.URLField()
    city = models.CharField(max_length=20)
    personalPage = models.ForeignKey(PersonalPage , unique=True)




class Employer(models.Model):
    companyName = models.CharField(max_length=30)
    PUBLIC = 0
    PRIVATE = 1
    SEMI_PRIVATE = 2

    COMPANY_TYPE_CHOICES = (
        (PUBLIC , 'دولتی') ,
        (PRIVATE , 'خصوصی'),
        (SEMI_PRIVATE , 'نیمه خصوصی'),
    )
    companyType = models.PositiveSmallIntegerField( choices=COMPANY_TYPE_CHOICES , default=PUBLIC)
    registrationNumber = models.CharField(max_length=20)
    contactEmail = models.EmailField()
    webSite = models.URLField()
    establishDate = models.DateField()
    user = models.ForeignKey(User , unique=True)


class JobSeeker(models.Model):
    birthDate = models.DateField()

    MALE = 0
    FEMALE = 1
    SEX_CHOICES = (
        (MALE , 'مرد'),
        (FEMALE , 'زن'),
    )
    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES , default=FEMALE)

    PART_TIME = 0
    FULL_TIME = 1
    UNEMPLOYED = 2
    JOB_STATUS_CHOICES = (
        (PART_TIME , 'پاره وقت'),
        (FULL_TIME , 'تمام وقت'),
        (UNEMPLOYED , 'بیکار'),
    )
    job_status = models.PositiveSmallIntegerField(choices=JOB_STATUS_CHOICES , default=UNEMPLOYED)

    cv = models.URLField()
    user = models.ForeignKey(User , unique=True)


class PersonalPage(models.Model):
    aboutMe = models.TextField(max_length=3000)
    background = models.TextField(max_length=3000)
    projects = models.TextField(max_length=3000)


class Record(models.Model):
    user = models.ForeignKey(User)
    startDate = models.DateField()
    endDate = models.DateField()
    position = models.CharField(max_length=20)
    companyName = models.CharField(max_length=30)

src/jobs/models.py
#coding=utf-8
from django.db                  import models
from django.utils.safestring    import mark_safe
from accounts.models            import Employer, JobSeeker
import social_network.models

class JobOpportunity(models.Model):
    user = models.ForeignKey(Employer)
    name = models.CharField(max_length=50)

    MALE = 0
    FEMALE = 1
    BOTH = 2

    SEX_CHOICES = (
        (MALE, 'مرد'),
        (FEMALE, 'زن'),
        (BOTH, 'مرد-زن'),
    )

    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES , default=BOTH)
    baseSalary = models.IntegerField()
    number = models.IntegerField()
    expireDate = models.DateField()


    def _get_rate(self):
        ratings = social_network.models.RateForOpportunity.objects.all().filter(opportunity__id = self.id)
        frate = 0.0
        for r in ratings:
            frate += r.rate
        if len(ratings) == 0 or frate == 0.0:
            frate = 0
        else:
            frate /= len(ratings)
        return int(round(frate))
    rate = property(_get_rate)

    def __unicode__(self):
        # return mark_safe('<a href="/jobs/' + str(self.id) + '/">' + self.name + '</a>')
        return self.name

class JobOpportunityPage(models.Model):
    opportunity = models.ForeignKey(JobOpportunity, related_name='pages')
    title   = models.CharField(max_length = 100)
    content = models.TextField(null=True, blank=True)
    
class Skill(models.Model):
    name = models.CharField(max_length=50, unique=True)
    user = models.ManyToManyField(JobSeeker, related_name = 'skills', blank = True, null = True)
    opportunity = models.ManyToManyField(JobOpportunity, related_name = 'opSkills', blank = True, null = True)
    class Meta:
        verbose_name = 'مهارت'
        verbose_name_plural = 'مهارت ها'

    def __unicode__(self):
        return self.name



class JobOffer(models.Model):
    jobSeeker = models.ForeignKey(JobSeeker)
    jobOpportunity = models.ForeignKey(JobOpportunity, related_name='offers')
    offerDate = models.DateField()

    ACCEPTED = 0
    REJECTED = 1
    PENDING = 2
    STATE_CHOICES = (
        (ACCEPTED , 'قبول شده'),
        (REJECTED ,'رد شده'),
        (PENDING ,'معلق'),
    )
    state = models.PositiveSmallIntegerField(choices=STATE_CHOICES , default=PENDING)

    JOBSEEKER_TO_EMPLOYER = 0
    EMPLOYER_TO_JOBSEEKER = 1
    MODE_CHOICES = (
        (JOBSEEKER_TO_EMPLOYER ,'کارجو به کارفرما'),
        (EMPLOYER_TO_JOBSEEKER ,'کارفرما به کارجو'),
    )
    mode = models.PositiveSmallIntegerField(choices=MODE_CHOICES , default=JOBSEEKER_TO_EMPLOYER)
    date = models.DateField(auto_now_add=True)

src/search/models.py
from django.db 				import models
from accounts.models 		import *

# Create your models here.
class SearchAgent(models.Model):
	user = models.ForeignKey(JobSeeker)
	start_date = models.DateField()
	min_wage = models.IntegerField(default=0)
	city = models.ManyToManyField(City)
	company_type = models.ManyToManyField(CompanyType)

src/search/views.py
from accounts.models import JobSeeker, Employer
from jobs.models import JobOpportunity, JobOffer
from social_network.models import RateForOpportunity, RateForEmployer
import json
import search
from django.shortcuts            import render
from django.http                 import HttpResponse
import math
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

@csrf_exempt
def opSearch(request):
    request.session['lastSearch'] = 'job'
    pageSize = 4
    curPage = 1
    user = request.user
    if request.method == "GET":
        param = request.GET
    elif request.method == 'POST':
        param = request.POST
    query = param.get('q') or ""
    print('query', query)
    skills = []
    try:
        skills = json.loads(param.get('sk'))
    except Exception as ex:
        print('ok')
        # print(type(ex).__name__)
        # print(ex.args)    

    try:
        curPage = int(param.get('page'))
    except Exception as ex:
        print type(ex).__name__
        print ex.args
        curPage = 1

    if curPage < 1:
        curPage = 1

    print("skills", skills)
    print('curPage', curPage)

    if not 'ajax' in param and user.is_authenticated() and len(skills) == 0:
        try:
            skillOb = JobSeeker.objects.all().get(user__username = user.username).skills.all()
            for sob in skillOb:
                skills.append(sob.name)
        except Exception as ex:
            # template = "An exception of type {0} occured. Arguments:\n{1!r}"
            # message = template.format(type(ex).__name__, ex.args)
            # print message
            skills = []

    search_result = search.opportunity(query, skills)
    start = (curPage - 1) * pageSize
    next = True
    pre = False
    count = len(search_result)
    
    if count < start + 1:
        search_result = search_result[0:pageSize]
    else:
        search_result = search_result[start:start+pageSize]
        if curPage > 1:
            pre = True
        if count <= curPage * pageSize:
            next = False


    pageNum = int(math.ceil((count + 0.0) / pageSize))
    pages = []
    if  pageNum <= 5:
        pages = [str(i + 1) for i in range(pageNum)]
    else:
        if curPage % 3 == 0:
            base = curPage - 2
        else:
            base = (curPage / 3) * 3 + 1
        if pageNum - curPage < 3:
            pages = ['1', '...', str(pageNum - 2), str(pageNum - 1), str(pageNum)]
        else:
            pages = [str(base), str(base + 1), str(base + 2), '...', str(pageNum)]

    appliedFor = JobOpportunity.objects.filter(offers__jobSeeker = request.userprofile).exclude(offers__state=2)
    pending = JobOpportunity.objects.filter(offers__jobSeeker = request.userprofile, offers__state=2)

    context = {'query':query, 'skills' : skills, 'skill_result' : [], 'search_result' : search_result, 'pages':pages, 'next':next, 'pre' : pre, 'curPage' : str(curPage), 'pending' : pending, 'appliedFor' : appliedFor}
    return render(request, 'search/opSearch.html', context)


def skillSearch(request):
    param = request.GET
    skills = []
    if 'q' in param:
        query = param.get('q')
        if len(query) > 0:
            skills = search.skill(query)
        else:
            skills = []
    # print(skills)
    context = {'skills' : [], 'skill_result' : skills, 'search_result' : []}
    return render(request, 'search/opSearch.html', context)    


@login_required
def updateRate(request):
    param = request.GET
    response={}
    if 'rate' in param:
        if 'op' in param:

            try:
                op = JobOpportunity.objects.get(id = int(param.get('op')))
                ratings = RateForOpportunity.objects.filter(user__user__username = request.user.username).filter(opportunity__id = op.id)
                if len(ratings) == 0:
                    seeker = JobSeeker.objects.get(user__username = request.user.username)
                    r = RateForOpportunity(user = seeker, opportunity = op, rate = int(param.get('rate')))
                    r.save()
                else:
                    ratings[0].rate = int(param.get('rate'))
                    ratings[0].save()
            except Exception as ex:
                print(type(ex).__name__)
                print(ex.args)
                response['result'] = 0
                print('here1')
                return HttpResponse(json.dumps(response), content_type="application/json")

            response['result'] = 1
            response['rate'] = op.rate
            # print('here2')
            return HttpResponse(json.dumps(response), content_type="application/json")

        elif 'emp' in param:
            try:
                emp = Employer.objects.get(id = int(param.get('emp')))
                ratings = RateForEmployer.objects.filter(user__user__username = request.user.username).filter(employer__id = emp.id)
                if len(ratings) == 0:
                    seeker = JobSeeker.objects.get(user__username = request.user.username)
                    r = RateForEmployer(user = seeker, employer = emp, rate = int(param.get('rate')))
                    r.save()

                else:
                    ratings[0].rate = int(param.get('rate'))
                    ratings[0].save()
            except Exception as ex:
                print(type(ex).__name__)
                print(ex.args)
                response['result'] = 0
                print('here1')
                return HttpResponse(json.dumps(response), content_type="application/json")

            response['result'] = 1
            response['rate'] = emp.rate
            # print('here2')
            return HttpResponse(json.dumps(response), content_type="application/json")

    response['result'] = 0
    # print('here3')
    return HttpResponse(json.dumps(response), content_type="application/json")

@csrf_exempt
@login_required
def userSearch(request):
    request.session['lastSearch'] = 'user'
    pageSize = 4
    curPage = 1
    if request.method == "GET":
        param = request.GET
    elif request.method == "POST":
        param = request.POST
    query = param.get('q') or ""
    print('query', query)
    skills = []
    try:
        skills = json.loads(param.get('sk'))
    except Exception as ex:
        print('ok')
        # print(type(ex).__name__)
        # print(ex.args)    

    try:
        curPage = int(param.get('page'))
    except Exception as ex:
        print type(ex).__name__
        print ex.args
        curPage = 1

    if curPage < 1:
        curPage = 1

    print("skills", skills)
    print('curPage', curPage)

    
    search_result = search.user(query, skills)
    start = (curPage - 1) * pageSize
    next = True
    pre = False
    count = len(search_result)

    if count < start + 1:
        search_result = search_result[0:pageSize]
    else:
        search_result = search_result[start:start+pageSize]
        if curPage > 1:
            pre = True
        if count <= curPage * pageSize:
            next = False


    pageNum = int(math.ceil((count + 0.0) / pageSize))
    pages = []
    if  pageNum <= 5:
        pages = [str(i + 1) for i in range(pageNum)]
    else:
        if curPage % 3 == 0:
            base = curPage - 2
        else:
            base = (curPage / 3) * 3 + 1
        if pageNum - curPage < 3:
            pages = ['1', '...', str(pageNum - 2), str(pageNum - 1), str(pageNum)]
        else:
            pages = [str(base), str(base + 1), str(base + 2), '...', str(pageNum)]

    context = {'query': query, 'skills' : skills, 'skill_result' : [], 'search_result' : search_result, 'pages':pages, 'next':next, 'pre' : pre, 'curPage' : str(curPage)} 
    return render(request, 'search/userSearch.html', context)

templates/search/opSearch.html
{% extends "page.html" %}
{% load staticfiles %}
{% load date_tags %}

{% block title %}جستجوی فرصت شغلی{% endblock %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
{% endblock style %}

{% block script %}
<script type="text/javascript" src="{% static 'js/jobs.js' %}"></script>
{% if user.is_authenticated %}
<script type="text/javascript" src="{% static 'js/search/user-search.js' %}"></script>
{% else %}
<script type="text/javascript" src="{% static 'js/search/visitor-search.js' %}"></script>
{% endif %}

{% endblock script %}


{% block page %}
	<div class="ui grid" id="main">
		<div class="four wide column">
			<h4 class="ui top attached inverted red header">
			  مهارت‌ها
			</h4>
			<div class="ui segment attached" id="side-segment">
				{% for s in skills %}
				<div class="ui label skill-tag">
					<i class="delete icon"></i>
				  	{{s}}
				</div>
				{% endfor %}
				
				<div class="ui horizontal divider" id="tag-divider">
				  <i class="add sign icon" id="add-sign"></i>
				</div>

				<div class="tag-search-input-parent">
					<div class="ui small icon input" id="tag-search-input">
					  <input type="text" placeholder="جستجوی مهارت...">
					  <i class="search icon"></i>
					</div>
				</div>

				<div class="ui animated list" id="tag-search-list">
					{% for sr in skill_result %}
				  	<a class="item tag-link">
				    <i class="add icon add-tag-icon"></i>
				    {{sr.name}}
				  	</a>
				  	{% endfor %}
				  
				</div>
				
			</div>
		</div>
		<div class="ten wide column" id="search-results">
			<h4 class="ui top attached inverted black header">
			  نتایج جستجو
			</h4>
			<div class="ui segment attached">

				{% for op in search_result %}

				<div class="ui grid opportunity">
					<div class="ten wide column opp-info">
						<h4 class="ui header opp-header">{{op.name}}</h4>
						<div class="ui list">
						  <div class="item">
						    <i class="User icon"></i>
						    {{ op.user.companyName}}
						  </div>
						  <div class="item">
						    <i class="home icon"></i>
						    {{op.user.address}}
						  </div>
						  <div class="item">
						  	<i class="thumbs up icon"></i>
						  	<div>امتیاز کنونی: {{op.user.rate}}</div>
						  	 <div id="emp{{op.id}}" class="ui small star rating user-rating" data-rating="{{op.user.rate}}">
							  <i class="icon"></i>
							  <i class="icon"></i>
							  <i class="icon"></i>
							  <i class="icon"></i>
							  <i class="icon"></i>
							</div>
						  </div>
						  

						</div>
					</div>
					<div class="five wide column opp-action">
						<div class="scoreboard">امتیاز کنونی : {{op.rate}}</div>
						<div class="ui star rating opp-rating" data-rating="{{op.rate}}">
						  <i class="icon"></i>
						  <i class="icon"></i>
						  <i class="icon"></i>
						  <i class="icon"></i>
						  <i class="icon"></i>
						</div>
                        {% if user.is_authenticated and op not in appliedFor %}
						<div id = "refuseButton{{ op.id }}" onclick="refuseJob({{ op.id }})" class="ui red vertical animated button opp-request" style="{% if op not in pending %}display: none{% endif %}">
						  <div class="hidden content">
						  	<i class="large remove icon"></i>
						  </div>
						  <div class="visible content">
						    لغو درخواست
						  </div>
						</div>
						<div id = "applyButton{{ op.id }}" onclick="applyJob({{ op.id }})" class="ui green vertical animated button opp-request" style="{% if op in pending %}display: none{% endif %}">
						  <div class="hidden content" >
						  	<i class="large mail icon"></i>
						  </div>
						  <div class="visible content">
						    ارسال درخواست
						  </div>
						</div>
						{% endif %}

						<div class="ui teal button opp-more" {% if not user.is_authenticated or op in appliedFor %} style="margin-top: 20px" {% endif %}>
						    اطلاعات کامل
						</div>
					</div>
					<ul class="op-info" style="display:none">
						<li>{{op.sex}}</li>
						<li>{{op.baseSalary}}</li>
						<li>{{op.number}}</li>
						<li>{% get_jalali_date op.expireDate %}</li>

						<li>{{op.user.companyName}}</li>	
						<li>{{op.user.companyType}}</li>
						<li>{{op.user.contactEmail}}</li>
						<li>{{op.user.phoneNumber}}</li>
						<li>{{op.user.webSite}}</li>
						<li>{{op.user.address}}</li>
						<li>{% if op.user.image %}{{op.user.image.url}}{% endif %}</li>
						<li>{{op.id}}</li>
						<li class="compId">{{op.user.id}}</li>
						<li> {{op.opSkills.all | join:"، "}}</li>
					</ul>
				</div>
				<div class="ui divider"></div>

				{% endfor %}



			</div>
			<div class="ui pagination menu" id="opp-pagination">
				{% if pre %}
				  <a class="icon item">
				    <i class="icon left arrow"></i>
				  </a>
				 {% endif %}
				 {% for page in pages %}
				  <a class="{% if page == curPage %} active {% endif %} item pagination-item">
				    {{page}}
				  </a>
			  		{% endfor %}
			  
			  {% if next %}
			  <a class="icon item">
			    <i class="icon right arrow"></i>
			  </a>
			  {% endif %}
			</div>
		</div>
	</div>
	
	<div class="ui small modal" id="moreModal">
	  <div class="header" id="opName">
	    نام فرصت شغلی
	  </div>
	  <div class="content">
	    <!-- <div class="left">
	      Content can appear on left
	    </div> -->
	    <div class="right">
	      <div id="companyImage"><img src="/media/1.png"/></div>
	      <div id = "companyList" class="ui list">
			  <div class="item">
			    <i class="User icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="bookmark icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="mail icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="phone icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="url icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="home icon"></i>
			    
			  </div>

			  <div class="item">
			    <i class="info icon"></i>
			    
			  </div>
			  
			</div>

			<div id = "opList" class="ui list">
			  <div class="item">
			    <i class="male icon" id="sex-one"></i>
			    <i class="female icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="dollar icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="plus icon"></i>
			    
			  </div>
			  <div class="item">
			    <i class="calendar icon"></i>
			    
			  </div>
			  
			  
			</div>
			<div class="clearfix"></div>
	    </div>
	  </div>
	  <div class="actions">
	    <div class="ui secondary button" id="closeModal">بستن</div>
	  </div>
	</div>
	<form id="postForm" method="post" action="/search/user">
		<input type="hidden" name="q">
		<input type="hidden" name="sk">
	</form>
	<div style="display:none" id="query">{{query}}</div>
{% endblock page %}

templates/search/userSearch.html
{% extends "page.html" %}
{% load staticfiles %}
{% load date_tags %}

{% block title %}جستجوی کارجو{% endblock %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
{% endblock style %}

{% block script %}
<!-- <script type="text/javascript" src="{% static 'js/search.js' %}"></script> -->
<script type="text/javascript" src="{% static 'js/search/seeker-search.js' %}"></script>

{% endblock script %}


{% block page %}
	<div class="ui grid" id="main">
		<div class="four wide column">
			<h4 class="ui top attached inverted red header">
			  مهارت‌ها
			</h4>
			<div class="ui segment attached" id="side-segment">
				{% for s in skills %}
				<div class="ui label skill-tag">
					<i class="delete icon"></i>
				  	{{s}}
				</div>
				{% endfor %}
				
				<div class="ui horizontal divider" id="tag-divider">
				  <i class="add sign icon" id="add-sign"></i>
				</div>

				<div class="tag-search-input-parent">
					<div class="ui small icon input" id="tag-search-input">
					  <input type="text" placeholder="جستجوی مهارت...">
					  <i class="search icon"></i>
					</div>
				</div>

				<div class="ui animated list" id="tag-search-list">
					{% for sr in skill_result %}
				  	<a class="item tag-link">
				    <i class="add icon add-tag-icon"></i>
				    {{sr.name}}
				  	</a>
				  	{% endfor %}
				  
				</div>
				
			</div>
		</div>
		<div class="ten wide column" id="search-results">
			<h4 class="ui top attached inverted black header">
			  نتایج جستجو
			</h4>
			<div class="ui segment attached">

				{% for op in search_result %}

				<div class="ui grid opportunity">
					<a href="#"><h4 class="ui header user-header">{{op.user.username}}</h4></a>
					<div class="four wide column userImage">
						<img src={{op.image.url}}/>
					</div>
					<div class="six wide column user-info">
						
						<div class="ui list">
						  <div class="item">
						    <i class="User icon"></i>
						    {{ op.user.first_name}} {{op.user.last_name}}
						  </div>
						  
						  <div class="item">
						    <i class="{% if op.sex == 0 %} male {% else %} female {% endif %} icon"></i>
						    {{op.get_sex_display}}
						  </div>
						  <div class="item">
						    <i class="info icon"></i>
						    {{op.get_job_status_display}}
						  </div>
						  <div class="item">
						    <i class="mail icon"></i>
						    {{op.user.email}}
						  </div>
						  

						</div>
					</div>
					<div class="five wide column opp-action">
						<div class="ui green vertical animated button opp-request" onclick="link('/userpanel/inbox/send/?to={{ op.user.username }}')">
						  <div class="hidden content" >
						  	<i class="large mail icon"></i>
						  </div>
						  <div class="visible content">
						    ارسال پیام
						  </div>
						</div>

						<div class="ui teal button opp-more" onclick="link('/user/{{ op.user.username }}')">
						    صفحه کاربری
						</div>
					</div>
					<ul class="op-info" style="display:none">
						<!-- <li>{{op.sex}}</li>
						<li>{{op.baseSalary}}</li>
						<li>{{op.number}}</li>
						<li></li>

						<li>{{op.user.companyName}}</li>	
						<li>{{op.user.companyType}}</li>
						<li>{{op.user.contactEmail}}</li>
						<li>{{op.user.phoneNumber}}</li>
						<li>{{op.user.webSite}}</li>
						<li>{{op.user.address}}</li>
						<li>{% if op.user.image %}{{op.user.image.url}}{% endif %}</li>
						<li>{{op.id}}</li>
						<li class="compId">{{op.user.id}}</li>
						<li> {{op.opSkills.all | join:" "}}</li> -->
					</ul>
				</div>
				<div class="ui divider"></div>

				{% endfor %}



			</div>
			<div class="ui pagination menu" id="opp-pagination">
				{% if pre %}
				  <a class="icon item">
				    <i class="icon left arrow"></i>
				  </a>
				 {% endif %}
				 {% for page in pages %}
				  <a class="{% if page == curPage %} active {% endif %} item pagination-item">
				    {{page}}
				  </a>
			  		{% endfor %}
			  
			  {% if next %}
			  <a class="icon item">
			    <i class="icon right arrow"></i>
			  </a>
			  {% endif %}
			</div>
		</div>
	</div>
	<form id="postForm" method="post" action="/search/op">
		<input type="hidden" name="q">
		<input type="hidden" name="sk">
	</form>
	<div style="display:none" id="query">{{query}}</div>
{% endblock page %}